import { DestinationsProvider } from '@/providers/DestinationsProvider'
import { MessageProvider } from '@/providers/MessageProvider'
import '@galactic-tours/ui/theme.css'
import type { Metadata } from 'next'
import { JSX } from 'react'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: JSX.Element | JSX.Element[]
}) {
  return (
    <html lang='en'>
      <body>
        <MessageProvider>
          <DestinationsProvider>{children}</DestinationsProvider>
        </MessageProvider>
      </body>
    </html>
  )
}
